# Site settings
title: Stay SaaSy 
header-img: img/home-bg.png
email: kristenleach24@gmail.com
copyright_name: KristenLeach
description: > # this means to ignore newlines until "baseurl:"
  Just a lady learning to code in the heart of Silicon Valley
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  KristenLeach
learn_profile: KristenLeach
email_username: kristenleach24@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
